import streamlit as st
# -*- coding: utf-8 -*-
"""Proyek Analisis Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ug4Ox4qIFDSo1koFA0XiNJE-ce12rECy

# Proyek Analisis Data: [Input Nama Dataset]
- **Nama:** [affriyanto]
- **Email:** [affriyanto@lintasarta.co.id]
- **ID Dicoding:** [affriyanto]

## Menentukan Pertanyaan Bisnis

- Pertanyaan 1                                                    
 Bagaimana tren perubahan tingkat polusi udara (PM2.5 dan PM10) di Aotizhongxin selama tahun 2013–2017
- Pertanyaan 2                                                    
 Bagaimana hubungan antara kondisi cuaca (suhu, tekanan udara, kecepatan angin) dengan tingkat polusi udara?

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import datetime as dt
import plotly.express as px
import plotly.graph_objects as go

sns.set(style="whitegrid")

"""## Data Wrangling

### Gathering Data
"""

# Load data
df = pd.read_csv("https://raw.githubusercontent.com/affriyanto/Projek-analisa-data-new/refs/heads/main/Untitled%20spreadsheet%20-%20PRSA_Data_Aotizhongxin_20130301-20170228%20affriyanto.csv")

# Tampilkan 5 baris pertama
st.write(df.head())

# Cek info data
st.write(df.info())

# Gabungkan kolom tanggal
df['date'] = pd.to_datetime(df[['year', 'month', 'day', 'hour']])

# Cek missing values
df.isna().sum()

# Hapus kolom yang tidak diperlukan
df.drop(['No'], axis=1, inplace=True)

# Imputasi missing value dengan interpolasi
df.interpolate(method='linear', inplace=True)

"""**Insight:**
- xxx
- xxx

### Assessing Data
"""



"""**Insight:**
- xxx
- xxx

### Cleaning Data
"""



"""**Insight:**
- xxx
- xxx

## Exploratory Data Analysis (EDA)

### Explore ...
"""



"""**Insight:**
- xxx
- xxx

## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""



"""### Pertanyaan 2:"""



"""**Insight:**
- xxx
- xxx

## Analisis Lanjutan (Opsional)
"""



"""## Conclusion

- Conclution pertanyaan 1
- Conclution pertanyaan 2
"""